config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|zh/ do
	  resources :bookings
	  resources :locations
	  mount Upmin::Engine => '/admin'
	#  root to: 'visitors#index'
	  root to: 'visitors#stylishPortfolio'
	  devise_for :users
	  resources :users
	  #map.resources :bookings, :path_prefix => '/:locale'
	  #map.resources :locations, :path_prefix => '/:locale'
	  #map.resources :users, :path_prefix => '/:locale'
  end
  
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user, :class_name => 'User', :foreign_key => 'user_id'
  belongs_to :server, :class_name => 'User', :foreign_key => 'server_id'
  
  validates_associated :user
  validates_presence_of :user_id 

  enum helper_class: [:Helper, :Nurse]
  enum trip_type: [:OneWay, :RoundTrip]
  enum status: [:Booked, :Confirmed, :Completed, :Cancelled, :Paid, :Voided]

  before_save :calculate_fee
  before_update :calculate_fee
  
  public
  def self.i18n_trip_types(hash = {})
    trip_types.key.each { |key| hash[I18n.t("")]}
  end
  
  private
    def calculate_fee
      self.total_fee = self.hours * 70
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    case current_user.role
    when :staff
      @bookings = Booking.where('server_id = ?', current_user.id)
    when :admin
      @bookings = Booking.all
    else
      @bookings = Booking.where('user_id = ? ', current_user.id)
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:user_id, :start_datetime, :end_datetime, :pickup_location_id, 
               :dropoff_location_id, :trip_type, :helper_class, :hourly_rate, :total_fee, :server_id, 
               :dropoff_address, :pickup_address, :hours, :status)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
 <div class="authform"> 
  <%= simple_form_for(@booking) do |f| %>

    <div class="form-inputs">



      <%= f.input :start_datetime %>
      <%#= f.input :end_datetime %>
      <%= f.input :hours, collection: 2..8 %>

      <%= f.input :pickup_address %>
      <%= f.input :dropoff_address %>

      <!--as: :radio_buttons %>  -->

      <%= f.input :trip_type do %>
        <%= f.select(:trip_type, Booking.trip_types.keys.map {| trip_type | [trip_type.titleize,trip_type]}) %>
      <% end %>

      <%= f.input :helper_class do %>
      <%= f.select(:helper_class, Booking.helper_classes.keys.map {| helper_class | [helper_class.titleize, helper_class]}) %>
      <% end %>
      
      <%= f.association :server, :as => :collection_select, collection: User.staff %>
      
      
      <%= f.select(:status, Booking.statuses.keys.map {|status| [status.titleize,status]}) %>
    </div>
    <br>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>

<%= link_to @booking do %>
  <i class="glyphicon glyphicon-zoom-in"></i>
<% end %>

<%= link_to bookings_path do %>
  <i class="glyphicon glyphicon-list"></i>
<% end %>

</div>

app/views/bookings/edit.html.erb
<%= render 'form' %>

app/views/bookings/index.html.erb
<h1><%= t :listing_booking %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th> 
      <th><%= t :start_datetime %></th>
      <th><%= t :duration %></th>
      <th><%= t :pickup %></th>
      <th><%= t :dropoff %></th>
      <th><%= t :trip_type %></th>
      <th><%= t :helper_class %></th>
      <th><%= t :total_fee %></th>
      <th><%= t :server %></th>
      <th><%= t :status %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user.name if booking.user %></td> 
        <td><%= booking.start_datetime.strftime("%d/%m/%y %I:%M%P")%></td>
        <td><%= booking.hours %><%= t :hours %></td>
        <td><%= booking.pickup_address %></td>
        <td><%= booking.dropoff_address %></td>
        <td><%= t booking.trip_type %></td>
        <td><%= t booking.helper_class %></td>
        <td><%= number_to_currency(booking.total_fee, precision: 0, unit: '$') %></td>
        <td><%= booking.server.name if booking.server %></td>
        <td><%= t booking.status %></td>

        <td>
            <%= link_to booking do %>
              <i class="glyphicon glyphicon-zoom-in"></i>
            <% end %>
        </td>
        <td>
            <%= link_to edit_booking_path(booking)  do %>
              <i class="glyphicon glyphicon-edit"></i>
            <% end %>
        </td>
<!--
        <td>
            <%= link_to booking, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="glyphicon glyphicon-trash"></i>
            <% end %>
        </td>
-->

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_booking_path do %>
  <i class="glyphicon glyphicon-plus-sign"></i>
<% end %>

app/views/bookings/new.html.erb
<%= render 'form' %>

app/views/bookings/show.html.erb
 <div class="authform"> 

<!--   <p>
    <strong>User:</strong> <%= @booking.user.name %>
  </p> -->
  <p>
<!--    <strong><%= t :start_datetime %>:</strong><%= @booking.start_datetime.to_formatted_s(:short)  %>-->
    <strong><%= t :start_datetime %>:</strong><%= @booking.start_datetime.strftime("%d/%m/%y %I:%M%P")%>
  </p>
  <p>
    <strong><%= t :no_of_hours %>:</strong> <%= @booking.hours %><%= t :hours %>
  </p>
  <p>
    <strong><%= t :pickup %>:</strong> <%= @booking.pickup_address %>
  </p>
  <p>
    <strong><%= t :dropoff %>:</strong> <%= @booking.dropoff_address %>
   </p>
  <p>
    <strong><%= t :trip_type %>:</strong> <%= t @booking.trip_type %>
  </p>
  <p>
    <strong><%= t :helper_class %>:</strong> <%=  t @booking.helper_class %>
  </p>
  <p>
    <strong><%= t :total_fee %>:</strong> $<%= @booking.total_fee %>
  </p>
  <p>
    <strong><%= t :server %>:<%= @booking.server.name if @booking.server%>
  </p>
  <p>
    <strong><%= t :status %>:</strong>  <%= t @booking.status %>
  </p>

  <%= link_to edit_booking_path(@booking)  do %>
    <i class="glyphicon glyphicon-edit"></i>
  <% end %>

  <%= link_to bookings_path do %>
    <i class="glyphicon glyphicon-list"></i>
  <% end %>

</div>