config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|zh/ do
	  resources :bookings
	  resources :locations
	  mount Upmin::Engine => '/admin'
	#  root to: 'visitors#index'
	  root to: 'visitors#stylishPortfolio'
	  devise_for :users
	  resources :users
	  #map.resources :bookings, :path_prefix => '/:locale'
	  #map.resources :locations, :path_prefix => '/:locale'
	  #map.resources :users, :path_prefix => '/:locale'
  end
  
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="container">
  <hr>
  <footer>
      <div class="row">
          <div class="col-lg-12">
              <p>Copyright &copy; WeCare 2016</p>
          </div>
      </div>
  </footer>
</div>
<!-- /.container -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to t('edit_account'), edit_user_registration_path %></li>
  <li><%= link_to t('sign_out'), destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to t('sign_in'), new_user_session_path %></li>
  <li><%= link_to t('sign_up'), new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to t('admin'), '/admin' %></li>
    <li><%= link_to t('users'), users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('home'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>
      

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
<%# add navigation links to this file %>
        <li><%= link_to t('about'), page_path('about') %></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('Booking')%><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to t('List_Booking'), bookings_path %></li>
                <li><%= link_to t('New_Booking'), new_booking_path %></li>      
                <li><%#= link_to '3 Column Portfolio', page_path('portfolio-3-col') %></li>
            </ul>
        <li><%= link_to 'English', url_for( :locale => 'en' ) %></li>         
        <li><%= link_to '中文', url_for( :locale => 'zh' ) %></li>
        </li>
<!--
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to 'Full Width Page', page_path('full-width') %></li>
                <li><%= link_to 'Sidebar Page', page_path('sidebar') %></li>
                <li><%= link_to 'FAQ', page_path('faq') %></li>
                <li><%= link_to '404', page_path('404') %></li>
                <li><%= link_to 'Pricing Table', page_path('pricing') %></li>
            </ul>
        </li>
-->
<% else %>
    <li><%= link_to 'English', url_for( :locale => 'en' ) %></li>         
    <li><%= link_to '中文', url_for( :locale => 'zh' ) %></li>
<% end %>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WeCare" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://js.stripe.com/v2" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>